# Generated by Django 3.2.4 on 2021-06-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_alter_leave_taken_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='taken_at',
        ),
        migrations.AddField(
            model_name='leave',
            name='approved',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='leave',
            name='taken_from',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AddField(
            model_name='leave',
            name='taken_till',
            field=models.DateTimeField(default='2021-01-01'),
        ),
        migrations.AddField(
            model_name='leave',
            name='type',
            field=models.CharField(blank=True, choices=[('EL', 'EL'), ('CL', 'CL'), ('CCL', 'CCL')], max_length=5),
        ),
    ]
