# Generated by Django 3.2.4 on 2021-06-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_auto_20210615_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='taken_till',
            field=models.DateField(default='2021-01-01'),
        ),
    ]
